using System;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace RustNet.Designer.Deployment;

/// <summary>
/// Compiles the code pane into an assembly the RNX compiler can read: a scratch
/// project next to the temp folder, project references to every
/// <c>RustNet.*</c> library in the checkout, and <c>dotnet build</c>.
///
/// Debug configuration on purpose — the interpreter only supports Debug-shaped
/// async state machines, so a Release build would compile fine and then fail on
/// the device.
/// </summary>
public static class AppBuilder
{
    public sealed record BuildResult(bool Ok, string AssemblyPath, string Log);

    /// <summary>
    /// Write <paramref name="source"/> into a scratch project named
    /// <paramref name="appName"/> and build it. The returned path is the DLL;
    /// on failure it is empty and the log holds the compiler output.
    /// </summary>
    public static Task<BuildResult> BuildAsync(
        string source,
        string appName,
        string workspaceRoot,
        Action<string> log,
        CancellationToken cancellationToken)
        => Task.Run(() =>
        {
            string safeName = Sanitize(appName);
            string dir = Path.Combine(Path.GetTempPath(), "rustnet-designer-build", safeName);
            string src = Path.Combine(workspaceRoot, "dotnet", "src");
            if (!Directory.Exists(src))
            {
                string message = $"No dotnet/src under {workspaceRoot} — set Assistant.WorkspaceRoot in app.config "
                    + "to the RustNet checkout so generated code has libraries to compile against.";
                log(message);
                return new BuildResult(false, "", message);
            }

            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "Program.cs"), source);
            File.WriteAllText(Path.Combine(dir, safeName + ".csproj"), Csproj(src, safeName));
            log($"project: {dir}");

            var output = new StringBuilder();
            int exit = RunDotnet($"build \"{Path.Combine(dir, safeName + ".csproj")}\" -c Debug --nologo",
                dir, line => { output.AppendLine(line); log(line); }, cancellationToken);

            string dll = Path.Combine(dir, "bin", "Debug", "net10.0", safeName + ".dll");
            if (exit != 0 || !File.Exists(dll))
            {
                return new BuildResult(false, "", output.ToString());
            }
            log($"built {Path.GetFileName(dll)}");
            return new BuildResult(true, dll, output.ToString());
        }, cancellationToken);

    /// <summary>
    /// A standalone project referencing every RustNet library, so whatever the
    /// code pane holds compiles without the person hand-editing references.
    /// Matches the shape the templates use.
    /// </summary>
    private static string Csproj(string srcDir, string appName)
    {
        var references = new StringBuilder();
        foreach (string project in Directory.EnumerateDirectories(srcDir, "RustNet.*").OrderBy(d => d))
        {
            string name = Path.GetFileName(project);
            string csproj = Path.Combine(project, name + ".csproj");
            if (File.Exists(csproj))
            {
                references.AppendLine($"    <ProjectReference Include=\"{csproj}\" />");
            }
        }
        return $"""
            <Project Sdk="Microsoft.NET.Sdk">
              <!-- Generated by the RustNet Designer for {appName}; safe to delete. -->
              <PropertyGroup>
                <OutputType>Exe</OutputType>
                <TargetFramework>net10.0</TargetFramework>
                <Nullable>enable</Nullable>
                <ImplicitUsings>enable</ImplicitUsings>
                <AssemblyName>{appName}</AssemblyName>
                <RootNamespace>{appName}</RootNamespace>
                <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
                <!-- Debug only: the interpreter models Debug-config async state machines. -->
                <Configuration>Debug</Configuration>
              </PropertyGroup>
              <ItemGroup>
                <Compile Include="Program.cs" />
              </ItemGroup>
              <ItemGroup>
            {references.ToString().TrimEnd()}
              </ItemGroup>
            </Project>
            """;
    }

    private static int RunDotnet(string arguments, string workingDirectory, Action<string> onLine,
        CancellationToken cancellationToken)
    {
        var psi = new ProcessStartInfo("dotnet", arguments)
        {
            WorkingDirectory = workingDirectory,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            CreateNoWindow = true,
        };
        using var process = new Process { StartInfo = psi };
        process.OutputDataReceived += (_, e) => { if (e.Data != null) { onLine(e.Data); } };
        process.ErrorDataReceived += (_, e) => { if (e.Data != null) { onLine(e.Data); } };
        process.Start();
        process.BeginOutputReadLine();
        process.BeginErrorReadLine();

        while (!process.WaitForExit(200))
        {
            if (cancellationToken.IsCancellationRequested)
            {
                try
                {
                    process.Kill(entireProcessTree: true);
                }
                catch (InvalidOperationException)
                {
                    // Already gone.
                }
                cancellationToken.ThrowIfCancellationRequested();
            }
        }
        process.WaitForExit();   // flush the async readers
        return process.ExitCode;
    }

    /// <summary>An app name that is legal as an assembly name and a device app id.</summary>
    public static string Sanitize(string name)
    {
        var sb = new StringBuilder();
        foreach (char c in name.Trim())
        {
            sb.Append(char.IsAsciiLetterOrDigit(c) ? c : '_');
        }
        string result = sb.ToString().Trim('_');
        return result.Length == 0 ? "app" : result;
    }
}
