<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\RustNet.Core\RustNet.Core.csproj" />
    <ProjectReference Include="..\..\src\RustNet.Diagnostics\RustNet.Diagnostics.csproj" />
  </ItemGroup>
</Project>
