//! The 64-bit microsecond timer, and the tick it will not run without.
//!
//! The RP2040's timer counts microseconds directly, which makes it the
//! pleasantest clock in this repository — no prescaler arithmetic, no wrap
//! handling for any plausible uptime.
//!
//! It has one prerequisite that is easy to miss and total when missed: the
//! timer is fed by a 1 MHz tick generated by the **watchdog** block, and that
//! tick is off at reset. Without [`start_tick`] the timer reads zero forever,
//! so every delay returns instantly and every timeout fires at once — which
//! looks like a hung peripheral somewhere else entirely.

use rustnet_hal::delay::Delay;

use crate::base::{TIMER, WATCHDOG};
use crate::{reg, resets};

const TIMER_TIMEHR: usize = TIMER + 0x08;
const TIMER_TIMELR: usize = TIMER + 0x0C;
const TIMER_TIMERAWH: usize = TIMER + 0x24;
const TIMER_TIMERAWL: usize = TIMER + 0x28;

const WATCHDOG_TICK: usize = WATCHDOG + 0x2C;
const WATCHDOG_TICK_ENABLE: u32 = 1 << 9;

/// Start the 1 MHz tick the timer counts.
///
/// `xosc_hz` is the crystal, because the tick divides the *reference* clock
/// rather than the system clock — so this stays correct whatever the PLL was
/// configured to, and a system clock change does not silently rescale time.
pub fn start_tick(xosc_hz: u32) -> bool {
    // The TIMER block is in RESETS like almost everything else, and this was
    // missed the first time this port was flashed. A held timer reads zero
    // forever, so `delay_us` computed a deadline it could never reach and spun
    // with the LED left on — a board that looks hung rather than one that
    // looks mistimed. The watchdog itself is not in RESETS; it is always on.
    if !resets::unreset(resets::TIMER) {
        return false;
    }
    let cycles = xosc_hz / 1_000_000;
    reg::write(WATCHDOG_TICK, WATCHDOG_TICK_ENABLE | cycles);

    // Confirm it is counting rather than assume it. Everything above this
    // depends on time, and a timer that never ticks makes every one of those
    // failures look like something else.
    let start = now_us();
    reg::wait_until(100_000, || now_us() != start)
}

/// Microseconds since the tick started.
///
/// Latched, not raw. Reading `TIMELR` freezes the high half so the two halves
/// belong to the same instant; reading them independently gives a value that
/// jumps by 2^32 whenever the low half wraps between the two reads — once
/// every 71 minutes, which is exactly long enough to ship.
pub fn now_us() -> u64 {
    let low = reg::read(TIMER_TIMELR);
    let high = reg::read(TIMER_TIMEHR);
    ((high as u64) << 32) | low as u64
}

/// The unlatched pair, for a caller that only wants the low half cheaply.
pub fn now_us_raw() -> u64 {
    let high = reg::read(TIMER_TIMERAWH);
    let low = reg::read(TIMER_TIMERAWL);
    ((high as u64) << 32) | low as u64
}

/// A [`Delay`] over the microsecond timer.
pub struct TimerDelay;

impl Delay for TimerDelay {
    fn delay_us(&mut self, us: u64) {
        let until = now_us().wrapping_add(us);
        // Bounded, like every other wait in this port, and for the reason this
        // port learned the hard way: a timer that is not running makes this a
        // deadline that can never arrive, and an unbounded spin there is a
        // board that appears dead rather than one whose timing is wrong. The
        // ceiling is far longer than any real delay, so a working timer never
        // reaches it.
        let mut guard = 0u32;
        // Signed difference rather than `now < until`: at 64 bits of
        // microseconds this cannot wrap in any lifetime, but writing it this
        // way costs nothing and stays correct if it ever could.
        while (now_us().wrapping_sub(until) as i64) < 0 {
            guard += 1;
            if guard == u32::MAX {
                return;
            }
            core::hint::spin_loop();
        }
    }

    fn delay_ms(&mut self, ms: u64) {
        self.delay_us(ms * 1000);
    }

    fn now_us(&self) -> u64 {
        now_us()
    }
}
