//! DVP — the camera interface.
//!
//! **The sensor's control channel is I²C2, not the DVP's SCCB master.** The
//! chip has both: a small SCCB master built into the DVP block, and the
//! ordinary I²C controllers, and either can reach the two pads the sensor's
//! control lines sit on. This port tried the SCCB master first — it is the one
//! named after the protocol, and Kendryte's own `dvp.c` drives it — and got a
//! sensor that acknowledged its address, answered `0x26` from the id register
//! once, and `0xff` on every boot after.
//!
//! A running MaixPy settles it, and says so out loud on the way up:
//!
//! ```text
//! init i2c:2 freq:100000
//! [MAIXPY]: find ov2640
//! ```
//!
//! Its FPIOA words confirm it — IO41 carries `I2C2_SCLK` and IO40 `I2C2_SDA`,
//! not the SCCB functions. So [`crate::i2c`] drives the sensor and this module
//! keeps only what is genuinely DVP: the pixel clock, the power and reset
//! lines, and the capture engine.
//!
//! ## The conflict with the panel
//!
//! The eight DVP data pins are the same eight the LCD is driven through — the
//! panel works precisely because `sysctl.misc.spi_dvp_data_enable` routes
//! SPI0's data onto them. So the camera and the display **cannot both be
//! streaming**: a capture needs that routing off, and a blit needs it on.
//! Capture, switch, display. MaixPy does the same, which is why its camera
//! examples snapshot and then draw rather than previewing continuously.
//!
//! ## Why the sensor needs a clock before it will answer
//!
//! `XCLK` is generated by this peripheral, and the sensor's own logic runs off
//! it — including the part that acknowledges an SCCB address. So the block has
//! to be clocked and out of power-down *before* a probe means anything, and a
//! probe that runs too early reads as an absent camera — and so does one that
//! runs while the sensor is still held in reset.

use rustnet_hal::delay::Delay;
use rustnet_hal::i2c::I2cBus;
use rustnet_hal::HalResult;

use crate::delay::CycleDelay;
use crate::{fpioa, reg, sysctl};

const DVP_BASE: usize = 0x5043_0000;

const DVP_CFG: usize = DVP_BASE + 0x00;
const R_ADDR: usize = DVP_BASE + 0x04;
const G_ADDR: usize = DVP_BASE + 0x08;
const B_ADDR: usize = DVP_BASE + 0x0C;
const CMOS_CFG: usize = DVP_BASE + 0x10;
const AXI: usize = DVP_BASE + 0x1C;
const STS: usize = DVP_BASE + 0x20;
const RGB_ADDR: usize = DVP_BASE + 0x28;

const CMOS_CLK_DIV_MASK: u32 = 0x0000_00FF;
const CMOS_CLK_ENABLE: u32 = 0x0000_0100;
const CMOS_RESET: u32 = 0x0001_0000;
const CMOS_POWER_DOWN: u32 = 0x0100_0000;

/// `dvp_cfg`: what the block emits, and how much of it.
const CFG_START_INT: u32 = 1 << 0;
const CFG_FINISH_INT: u32 = 1 << 1;
const CFG_AI_OUTPUT: u32 = 1 << 2;
const CFG_DISPLAY_OUTPUT: u32 = 1 << 3;
const CFG_FORMAT_MASK: u32 = 0x0000_0600;
/// The format arriving on the wire, not the format the block writes out. The
/// OV2640 is configured for YUV422 here even though the display output is
/// RGB565 — MaixPy does the same, and the block converts.
const CFG_FORMAT_YUV: u32 = 0x0000_0200;
const CFG_HREF_BURST_MASK: u32 = 0x000F_F000;
const CFG_LINE_NUM_MASK: u32 = 0x3FF0_0000;

const AXI_GM_MLEN_MASK: u32 = 0x0000_00FF;
const AXI_GM_MLEN_1BYTE: u32 = 0;

/// `sts`: each state bit is paired with a write-enable bit one place above it,
/// so a write only touches the bits it also enables. That is what makes it
/// safe to acknowledge one event mid-frame without disturbing another.
const STS_FRAME_START: u32 = 1 << 0;
const STS_FRAME_START_WE: u32 = 1 << 1;
const STS_FRAME_FINISH: u32 = 1 << 8;
const STS_FRAME_FINISH_WE: u32 = 1 << 9;
const STS_DVP_EN: u32 = 1 << 16;
const STS_DVP_EN_WE: u32 = 1 << 17;

/// Iterations to allow a frame to arrive. Generous — a 320x240 frame at the
/// OV2640's default rate takes tens of milliseconds — but bounded, because a
/// sensor that never raises `vsync` would otherwise hang the firmware.
const FRAME_SPIN_LIMIT: u32 = 200_000_000;

/// Cached SRAM starts here; the same memory is aliased uncached 0x4000_0000
/// lower.
const CACHED_SRAM_BASE: u32 = 0x8000_0000;

/// The address the DVP must be given for a buffer the CPU allocated.
///
/// The block is an AXI master writing straight into SRAM, with no idea the CPU
/// has a cache. Hand it a cached address and the frame lands in memory while
/// the CPU keeps reading whatever the cache still holds. Kendryte's driver
/// asserts on a cached address rather than translating; this translates, and
/// the caller reads the frame back through the same alias.
pub const fn uncached(address: u32) -> u32 {
    if address >= CACHED_SRAM_BASE {
        address - 0x4000_0000
    } else {
        address
    }
}


/// The camera pads on a Maix Go, from the datasheet's pin table.
#[derive(Clone, Copy)]
pub struct CameraPins {
    pub sda: u8,
    pub scl: u8,
    pub reset: u8,
    pub vsync: u8,
    pub power_down: u8,
    pub href: u8,
    pub xclk: u8,
    pub pclk: u8,
}

pub const MAIX_CAMERA: CameraPins = CameraPins {
    sda: 40,
    scl: 41,
    reset: 42,
    vsync: 43,
    power_down: 44,
    href: 45,
    xclk: 46,
    pclk: 47,
};

/// OV2640 registers named in the bring-up sequence, from MaixPy's
/// `ov2640_regs.h`. The bare numbers in [`OV2640_DEFAULT`] are deliberately
/// left as numbers.
const REG_COM7: u8 = 0x12;
const COM7_SOFT_RESET: u8 = 0x80;
/// DSP bypass. The output scaler has to be switched out of circuit while its
/// size registers are rewritten, or it scales from half-updated values.
const REG_BYPASS: u8 = 0x05;
const BYPASS_DSP_ON: u8 = 0x00;
const BYPASS_DSP_OFF: u8 = 0x01;
/// Output width, height, and their high bits. Both are stored divided by four.
const REG_ZMOW: u8 = 0x5A;
const REG_ZMOH: u8 = 0x5B;
const REG_ZMHH: u8 = 0x5C;
/// DSP-bank reset control, and the bit that resets the DVP output stage.
const REG_RESET: u8 = 0xE0;
const RESET_DVP: u8 = 0x04;
const BANK_DSP: u8 = 0x00;

/// The sensor's registers holding its identity. Common to the OV series.
const REG_PID_HIGH: u8 = 0x0A;
const REG_PID_LOW: u8 = 0x0B;

/// Bank select, and the value that picks the sensor bank.
///
/// The OV2640 splits its register space in two, and `0x0A` means different
/// things in each. Read it without selecting the sensor bank first and the DSP
/// bank answers instead — this port read `0x2fff` that way, which looks like a
/// nearly-recognisable id and is not one.
const REG_BANK_SELECT: u8 = 0xFF;
const BANK_SENSOR: u8 = 0x01;

/// Product ids worth naming. The OV2640 answers `0x26xx`.
pub fn identify(pid: u16) -> Option<&'static str> {
    match pid {
        0x2640..=0x2643 => Some("OV2640"),
        0x7640..=0x7642 => Some("OV7640"),
        0x7720..=0x7725 => Some("OV7725"),
        0x9650..=0x9657 => Some("OV9650"),
        _ => None,
    }
}

pub struct Dvp {
    delay: CycleDelay,
}

impl Dvp {
    /// Mux the camera pads: the control bus onto I²C2, the rest onto the DVP.
    pub fn new(pins: CameraPins, cpu_hz: u32) -> Self {
        sysctl::clock_enable(sysctl::Peripheral::Fpioa);
        // I²C2, not SCCB — see the module note.
        fpioa::set_function(pins.sda, fpioa::I2C2_SDA);
        fpioa::set_function(pins.scl, fpioa::I2C2_SCLK);
        fpioa::set_function(pins.reset, fpioa::CMOS_RST);
        fpioa::set_function(pins.vsync, fpioa::CMOS_VSYNC);
        fpioa::set_function(pins.power_down, fpioa::CMOS_PWDN);
        fpioa::set_function(pins.href, fpioa::CMOS_HREF);
        fpioa::set_function(pins.xclk, fpioa::CMOS_XCLK);
        fpioa::set_function(pins.pclk, fpioa::CMOS_PCLK);

        Self { delay: CycleDelay::new(cpu_hz) }
    }

    /// Clock the block, start `XCLK`, and take the sensor out of power-down and
    /// reset.
    ///
    /// The order and the waits are Kendryte's `dvp_init` and `dvp_reset`: power
    /// down, hold, release, then reset low, hold, release. Sensors want real
    /// milliseconds here, not a few register writes in a row.
    pub fn init(&mut self) {
        sysctl::clock_enable(sysctl::Peripheral::Dvp);
        sysctl::reset(sysctl::Peripheral::Dvp);

        // XCLK = the DVP clock divided down. Divisor 3 is what the SDK uses,
        // and what a running MaixPy has in `cmos_cfg`.
        reg::modify(CMOS_CFG, CMOS_CLK_DIV_MASK, 3 | CMOS_CLK_ENABLE);

        // Power down, then up.
        reg::modify(CMOS_CFG, 0, CMOS_POWER_DOWN);
        self.delay.delay_ms(200);
        reg::modify(CMOS_CFG, CMOS_POWER_DOWN, 0);
        // MaixPy leaves `cmos_cfg` with the reset bit *set*, i.e. released, so
        // the line is active-low and not inverted on this board.
        self.delay.delay_ms(200);
        self.pulse_reset(false);
    }

    /// Pulse the sensor's reset. `inverted` swaps which level asserts it.
    ///
    /// Boards disagree about this line's polarity, which is why MaixPy retries
    /// its whole bring-up with the other one rather than picking a side. A
    /// sensor held in reset acknowledges its address and then answers every
    /// register with `0xff`, which looks like a bus fault rather than a reset.
    pub fn pulse_reset(&mut self, inverted: bool) {
        let (assert, release) = if inverted {
            (CMOS_RESET, 0)
        } else {
            (0, CMOS_RESET)
        };
        reg::modify(CMOS_CFG, release, assert);
        self.delay.delay_ms(200);
        reg::modify(CMOS_CFG, assert, release);
        self.delay.delay_ms(200);
    }

    /// Point the block at its output buffers and tell it the frame shape.
    ///
    /// `rgb` receives RGB565 ready to blit; `ai` receives the same frame as
    /// three planes of 8-bit R, G and B, which is what the KPU wants. Both
    /// outputs are enabled because MaixPy enables both, and a block configured
    /// for one output only is a variation this port has not tried on glass.
    ///
    /// All four addresses must be uncached — see [`uncached`].
    pub fn configure(&mut self, width: u16, height: u16, rgb: u32, ai: [u32; 3]) {
        // Burst mode changes what `href_burst_num` counts, so it has to be
        // settled before the size is written. MaixPy runs the OV2640 without
        // it, which makes a burst eight pixels.
        let mut cfg = CFG_START_INT | CFG_FINISH_INT | CFG_AI_OUTPUT | CFG_DISPLAY_OUTPUT;
        cfg |= CFG_FORMAT_YUV & CFG_FORMAT_MASK;
        cfg |= ((width as u32 / 8) << 12) & CFG_HREF_BURST_MASK;
        cfg |= ((height as u32) << 20) & CFG_LINE_NUM_MASK;
        reg::write(DVP_CFG, cfg);
        reg::modify(AXI, AXI_GM_MLEN_MASK, AXI_GM_MLEN_1BYTE);

        reg::write(R_ADDR, ai[0]);
        reg::write(G_ADDR, ai[1]);
        reg::write(B_ADDR, ai[2]);
        reg::write(RGB_ADDR, rgb);
    }

    /// Capture one whole frame into the configured buffers.
    ///
    /// Two frame starts are waited for, not one. Arriving mid-frame and
    /// enabling there would write a partial image and report success; the
    /// first start is discarded so the capture begins on a boundary, and the
    /// block is enabled only at the second.
    pub fn capture(&mut self) -> HalResult<()> {
        self.wait_for_frame_start()?;
        reg::write(STS, STS_FRAME_START | STS_FRAME_START_WE);
        self.wait_for_frame_start()?;
        reg::write(
            STS,
            STS_FRAME_START
                | STS_FRAME_START_WE
                | STS_FRAME_FINISH
                | STS_FRAME_FINISH_WE
                | STS_DVP_EN
                | STS_DVP_EN_WE,
        );
        for _ in 0..FRAME_SPIN_LIMIT {
            if reg::read(STS) & STS_FRAME_FINISH != 0 {
                reg::write(STS, STS_FRAME_FINISH | STS_FRAME_FINISH_WE);
                return Ok(());
            }
            core::hint::spin_loop();
        }
        Err(rustnet_hal::HalError::Timeout)
    }

    fn wait_for_frame_start(&mut self) -> HalResult<()> {
        for _ in 0..FRAME_SPIN_LIMIT {
            if reg::read(STS) & STS_FRAME_START != 0 {
                return Ok(());
            }
            core::hint::spin_loop();
        }
        Err(rustnet_hal::HalError::Timeout)
    }
}

/// The OV2640's 7-bit I²C address. `0x60` is its 8-bit write form, which is
/// the number the datasheets and MaixPy's logs quote.
pub const OV2640_ADDRESS: u8 = 0x30;

/// Read one sensor register.
///
/// Two transactions with a stop between, not a repeated start: this bus is
/// SCCB underneath, and a combined transfer is the classic way to read `0xff`
/// from a sensor that is perfectly present.
pub fn sensor_read(bus: &mut dyn I2cBus, address: u8, register: u8) -> HalResult<u8> {
    let mut value = [0u8; 1];
    bus.write(address, &[register])?;
    bus.read(address, &mut value)?;
    Ok(value[0])
}

pub fn sensor_write(bus: &mut dyn I2cBus, address: u8, register: u8, value: u8) -> HalResult<()> {
    bus.write(address, &[register, value])
}

/// The sensor's 16-bit product id, selecting the sensor bank first.
///
/// The OV2640 splits its register space in two and `0x0a` means different
/// things in each; read without selecting the sensor bank, the DSP bank
/// answers instead.
pub fn product_id(bus: &mut dyn I2cBus, address: u8) -> HalResult<u16> {
    let _ = sensor_write(bus, address, REG_BANK_SELECT, BANK_SENSOR);
    let high = sensor_read(bus, address, REG_PID_HIGH)?;
    let low = sensor_read(bus, address, REG_PID_LOW)?;
    Ok(((high as u16) << 8) | low as u16)
}

/// Ask the sensors this board might carry, at the addresses they use.
pub fn probe(bus: &mut dyn I2cBus) -> Option<(u8, u16)> {
    for address in [OV2640_ADDRESS, 0x21, 0x3C] {
        if let Ok(pid) = product_id(bus, address) {
            if identify(pid).is_some() {
                return Some((address, pid));
            }
        }
    }
    None
}

/// The OV2640 bring-up table, verbatim from MaixPy's `ov2640.c` (`ov2640_default`,
/// OpenMV, MIT). Two hundred-odd magic numbers that configure the sensor's
/// analogue front end, its DSP, and its output timing; OmniVision publishes no
/// register documentation for most of them, so this is a table to copy rather
/// than a sequence to understand.
pub const OV2640_DEFAULT: [(u8, u8); 158] = [
    (0xff, 0x01), (0x12, 0x80), (0xff, 0x00), (0x2c, 0xff),
    (0x2e, 0xdf), (0xff, 0x01), (0x3c, 0x32), (0x11, 0x00),
    (0x09, 0x02), (0x04, 0xa8), (0x13, 0xe5), (0x14, 0x48),
    (0x2c, 0x0c), (0x33, 0x78), (0x3a, 0x33), (0x3b, 0xfb),
    (0x3e, 0x00), (0x43, 0x11), (0x16, 0x10), (0x39, 0x92),
    (0x23, 0x00), (0x36, 0x1a), (0x07, 0xc0), (0x4c, 0x00),
    (0x48, 0x00), (0x5b, 0x00), (0x4a, 0x81), (0x21, 0x99),
    (0x24, 0x40), (0x25, 0x38), (0x26, 0x82), (0x5c, 0x00),
    (0x63, 0x00), (0x46, 0x22), (0x0c, 0x3c), (0x61, 0x70),
    (0x62, 0x80), (0x7c, 0x05), (0x20, 0x80), (0x28, 0x30),
    (0x6c, 0x00), (0x6d, 0x80), (0x6e, 0x00), (0x70, 0x02),
    (0x71, 0x94), (0x73, 0xc1), (0x5a, 0x57), (0x37, 0xc0),
    (0x4f, 0xca), (0x50, 0xa8), (0x5a, 0x23), (0x6d, 0x00),
    (0x3d, 0x38), (0xff, 0x00), (0xe5, 0x7f), (0xf9, 0xc0),
    (0x41, 0x24), (0xe0, 0x14), (0x76, 0xff), (0x33, 0xa0),
    (0x42, 0x20), (0x43, 0x18), (0x4c, 0x00), (0x87, 0xd5),
    (0x88, 0x3f), (0xd9, 0x10), (0xd3, 0x82), (0xc8, 0x08),
    (0xc9, 0x80), (0x7c, 0x00), (0x7d, 0x00), (0x7c, 0x03),
    (0x7d, 0x48), (0x7d, 0x48), (0x7c, 0x08), (0x7d, 0x20),
    (0x7d, 0x10), (0x7d, 0x0e), (0x90, 0x00), (0x91, 0x0e),
    (0x91, 0x1a), (0x91, 0x31), (0x91, 0x5a), (0x91, 0x69),
    (0x91, 0x75), (0x91, 0x7e), (0x91, 0x88), (0x91, 0x8f),
    (0x91, 0x96), (0x91, 0xa3), (0x91, 0xaf), (0x91, 0xc4),
    (0x91, 0xd7), (0x91, 0xe8), (0x91, 0x20), (0x92, 0x00),
    (0x93, 0x06), (0x93, 0xe3), (0x93, 0x05), (0x93, 0x05),
    (0x93, 0x00), (0x93, 0x04), (0x93, 0x00), (0x93, 0x00),
    (0x93, 0x00), (0x93, 0x00), (0x93, 0x00), (0x93, 0x00),
    (0x93, 0x00), (0x96, 0x00), (0x97, 0x08), (0x97, 0x19),
    (0x97, 0x02), (0x97, 0x0c), (0x97, 0x24), (0x97, 0x30),
    (0x97, 0x28), (0x97, 0x26), (0x97, 0x02), (0x97, 0x98),
    (0x97, 0x80), (0x97, 0x00), (0x97, 0x00), (0xc3, 0xef),
    (0xa4, 0x00), (0xa8, 0x00), (0xc5, 0x11), (0xc6, 0x51),
    (0xbf, 0x80), (0xc7, 0x10), (0xb6, 0x66), (0xb8, 0xa5),
    (0xb7, 0x64), (0xb9, 0x7c), (0xb3, 0xaf), (0xb4, 0x97),
    (0xb5, 0xff), (0xb0, 0xc5), (0xb1, 0x94), (0xb2, 0x0f),
    (0xc4, 0x5c), (0x5a, 0xc8), (0x5b, 0x96), (0x5c, 0x00),
    (0xc3, 0xed), (0x7f, 0x00), (0xe5, 0x1f), (0xdd, 0x7f),
    (0x05, 0x00), (0xff, 0x01), (0x12, 0x02), (0xff, 0x00),
    (0xe0, 0x04), (0xc2, 0x0c), (0xd7, 0x01), (0xda, 0x01),
    (0xe1, 0x67), (0xe0, 0x00),
];

/// The SVGA (800x600) DSP input configuration, also from `ov2640.c`. The
/// output scaler then crops and scales that down to whatever `set_framesize`
/// asks for, which is why a 320x240 frame still starts here.
pub const OV2640_SVGA: [(u8, u8); 29] = [
    (0xff, 0x01), (0x35, 0xda), (0x22, 0x1a), (0x37, 0xc3),
    (0x34, 0xc0), (0x06, 0x88), (0x0d, 0x87), (0x0e, 0x41),
    (0x42, 0x03), (0x3d, 0x34), (0x12, 0x40), (0x03, 0x0f),
    (0x17, 0x11), (0x18, 0x43), (0x19, 0x00), (0x1a, 0x4b),
    (0x32, 0x09), (0xff, 0x00), (0xc0, 0x64), (0xc1, 0x4b),
    (0x8c, 0x00), (0x86, 0x3d), (0x50, 0x00), (0x51, 0xc8),
    (0x52, 0x96), (0x53, 0x00), (0x54, 0x00), (0x55, 0x00),
    (0xd3, 0x02),
];

/// Bring the sensor up and configure it for `width` x `height` output.
///
/// The order is MaixPy's `reset` followed by its `set_framesize`, and neither
/// half works alone: the default table leaves the sensor at SVGA, and the size
/// registers mean nothing until the DSP has been configured.
pub fn configure(
    bus: &mut dyn I2cBus,
    address: u8,
    width: u16,
    height: u16,
    delay: &mut dyn Delay,
) -> HalResult<()> {
    sensor_write(bus, address, REG_BANK_SELECT, BANK_SENSOR)?;
    sensor_write(bus, address, REG_COM7, COM7_SOFT_RESET)?;
    delay.delay_ms(10);

    for (register, value) in OV2640_DEFAULT.iter().chain(OV2640_SVGA.iter()) {
        sensor_write(bus, address, *register, *value)?;
    }

    // Take the scaler out of circuit, resize, put it back.
    sensor_write(bus, address, REG_BANK_SELECT, BANK_DSP)?;
    sensor_write(bus, address, REG_BYPASS, BYPASS_DSP_OFF)?;
    for (register, value) in OV2640_SVGA.iter() {
        sensor_write(bus, address, *register, *value)?;
    }

    // Both sizes are held divided by four, with the odd high bits gathered
    // into ZMHH. The RESET_DVP bracket is MaixPy's: the output stage latches
    // these, and rewriting them unbracketed can leave it latched half-way.
    sensor_write(bus, address, REG_RESET, RESET_DVP)?;
    sensor_write(bus, address, REG_ZMOW, ((width >> 2) & 0xFF) as u8)?;
    sensor_write(bus, address, REG_ZMOH, ((height >> 2) & 0xFF) as u8)?;
    sensor_write(
        bus,
        address,
        REG_ZMHH,
        (((height >> 8) & 0x04) | ((width >> 10) & 0x03)) as u8,
    )?;
    sensor_write(bus, address, REG_RESET, 0x00)?;

    sensor_write(bus, address, REG_BANK_SELECT, BANK_DSP)?;
    sensor_write(bus, address, REG_BYPASS, BYPASS_DSP_ON)?;
    delay.delay_ms(30);
    Ok(())
}

/// Disconnect SPI0's data lines from the DVP pins so a capture can use them.
///
/// The inverse of what the panel needs. Whichever is set last owns the bus, so
/// a driver that captures has to put this back before the next `Present`.
pub fn release_pins_from_panel() {
    sysctl::set_spi0_dvp_data(false);
}

/// Give the pins back to the panel.
pub fn return_pins_to_panel() {
    sysctl::set_spi0_dvp_data(true);
}

/// Is the DVP capture engine running? Reported so a caller can tell "no
/// camera" from "camera never started".
pub fn is_enabled() -> bool {
    reg::read(DVP_CFG) != 0
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_camera_sits_on_the_documented_pads() {
        assert_eq!(MAIX_CAMERA.sda, 40);
        assert_eq!(MAIX_CAMERA.scl, 41);
        assert_eq!(MAIX_CAMERA.xclk, 46);
        assert_eq!(MAIX_CAMERA.pclk, 47);
    }

    /// The two halves of the bring-up sequence are copied tables, so what is
    /// worth guarding is that they arrived intact, not what they say.
    #[test]
    fn the_bring_up_tables_are_the_ones_that_were_copied() {
        assert_eq!(OV2640_DEFAULT.len(), 158);
        assert_eq!(OV2640_SVGA.len(), 29);
        // Both open by selecting a bank; a table that started anywhere else
        // would be writing into whichever bank was left selected.
        assert_eq!(OV2640_DEFAULT[0], (REG_BANK_SELECT, BANK_SENSOR));
        assert_eq!(OV2640_SVGA[0], (REG_BANK_SELECT, BANK_SENSOR));
        // The sentinel row the C tables end with must not have survived the
        // transcription: writing 0x00 to register 0x00 is a real write.
        assert!(!OV2640_DEFAULT.contains(&(0x00, 0x00)));
    }

    /// The DVP writes into SRAM past the cache, so every address it is handed
    /// has to be the uncached alias.
    #[test]
    fn buffer_addresses_are_translated_out_of_the_cache() {
        assert_eq!(uncached(0x8000_0000), 0x4000_0000);
        assert_eq!(uncached(0x8040_0000), 0x4040_0000);
        // Already uncached, or not SRAM at all: left alone rather than dragged
        // below the memory map.
        assert_eq!(uncached(0x4000_0000), 0x4000_0000);
    }

    #[test]
    fn the_ov2640_family_is_recognised() {
        assert_eq!(identify(0x2642), Some("OV2640"));
        assert_eq!(identify(0x7725), Some("OV7725"));
        assert_eq!(identify(0x0000), None);
        assert_eq!(identify(0xFFFF), None);
    }
}
